name: Generate Snake - Simple

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: DanielBarbieri21
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Generate snake" || exit 0
          git push
